FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY package*.json ./
COPY packages ./packages
COPY apps/backend ./apps/backend
RUN npm install
RUN cd apps/backend && npm install
EXPOSE 5000
CMD ["npm", "run", "dev", "--workspace=backend"]
